// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Prevozi.WebApi.Data;

#nullable disable

namespace Prevozi.WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250930203321_nova")]
    partial class nova
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Prevozi.WebApi.Models.Carrier", b =>
                {
                    b.Property<string>("registrationNumber")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("contactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("contactPerson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("contactPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("registrationNumber");

                    b.ToTable("carriers");
                });

            modelBuilder.Entity("Prevozi.WebApi.Models.Client", b =>
                {
                    b.Property<string>("registrationNumber")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("contactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("contactPerson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("contactPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("registrationNumber");

                    b.ToTable("clients");
                });

            modelBuilder.Entity("Prevozi.WebApi.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("carrierRegistrationNumber")
                        .HasColumnType("character varying(10)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("userRole")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("carrierRegistrationNumber");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Prevozi.WebApi.Models.User", b =>
                {
                    b.HasOne("Prevozi.WebApi.Models.Carrier", "carrier")
                        .WithMany()
                        .HasForeignKey("carrierRegistrationNumber");

                    b.Navigation("carrier");
                });
#pragma warning restore 612, 618
        }
    }
}
